model:
  base_learning_rate: 1.0e-05
  target: st-gcn-master.feeder.Feeder
  params:
    linear_start: 0.00085
    linear_end: 0.012
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: 'image'
    cond_stage_key: 'caption'
    image_size: 36
    channels: 2
    cond_stage_trainable: True
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    scale_factor: 0.18215
    use_ema: False

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 36
        in_channels: 2
        out_channels: 2
        model_channels: 256
        attention_resolutions:
        - 4
        - 2
        - 1
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 4
        num_heads: 8
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: True
        legacy: False

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 3
        monitor: val/rec_loss
        ckpt_path: "" #autoencoder.ckpt
        ddconfig:
          double_z: true
          z_channels: 3
          resolution: 36
          in_channels: 2
          out_ch: 2
          ch: 128
          ch_mult:
          - 1
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.encoders.modules.BERTEmbedder
      params:
        n_embed: 768
        n_layer: 32

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 4
    wrap: False
    train:
      target: ldm.data.traffic.TrafficTrain
      params:
        size: 36
    validation:
      target: ldm.data.traffic.TrafficValidation
      params:
        size: 36

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 32
        increase_log_steps: True

  trainer:
    benchmark: True



